{{- if .Values.app.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-configmap
  labels:
    app: {{ .Release.Name }}
data:
  DATABASE_HOST: {{ .Release.Name }}-db-service
  DATABASE_NAME: {{ .Release.Name }}-db
  DATABASE_USER: {{ .Values.db.user }}
  DATABASE_PASSWORD: {{ .Values.db.password }}
  DATABASE_URI: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Release.Name }}-db-service/{{ .Release.Name }}-db"
{{- end }}