#for application
{{- if not .Values.database.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  app-configmap
  labels:
    app: {{ .Release.Name }}
data:
  DATABASE_HOST: {{ .Release.Name }}-db-service
  DATABASE_NAME: {{ .Release.Name }}-database
  DATABASE_USER: {{ .Values.db.user }}
  DATABASE_PASSWORD: {{ .Values.db.password }}
{{- end }}