#true to take app deploy.yaml
database:
  enabled: "__DB_ENABLE__"

replicaCount: "__REPLICA_COUNT__"
image: 
  repository: "__IMAGE__"
  tag: "__TAG__"
  pullPolicy: "__IMAGE_PULL_POL__"
targetPort: "__CONT_PORT__"


#Service
service:
  port: "__SERVICE_PORT__"
  type: "__SERVICE_TYPE__"

#Volume mount
mountName: "__MOUNT_NAME__"
mountPath: "__MOUNT_PATH__"

#PVC & PV
pvc:
  enabled: "__PVC_EN__"
  storageClassName: "__STORAGE_CLASS_NAME__"

#Configmap for DB creds
db: 
  user: "__DB_USER__"
  password: "__DB_PASSWORD__"



